server:
  port: 7020
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/cerdasdb
    username: root
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  jooq:
#      sql-dialect: mysql
#  sql:
#    init:
#      mode: always
      